### ISSUE TITLE
Issues list to address AAACT's manual testing and usability findings

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-accessibility-passport#104]
Please find the preliminary review report findings below: [https://app.zenhub.com/files/477804994/6e7f6d7d-1f6e-48d2-8f10-72da057fd96a/download](https://app.zenhub.com/files/477804994/6e7f6d7d-1f6e-48d2-8f10-72da057fd96a/download)

**Comment by mnigh** [comment]
List of issues created based on AAACT document:

1. #105
2. #106
3. #107 
4. #108 
5. #109 
6. #110 
7. #111 
8. #112 
9. #113 
10. #114 
11. #115 
12. #116 
13. #117 
14. #118 
15. #119 
16. #120

**Comment by mnigh** [comment]
Closing issue as [separate issues](https://github.com/GCTC-NTGC/gc-accessibility-passport/issues/104#issuecomment-1137427445) were created based on the list.
