### ISSUE TITLE
Keyboard focus always goes to the top of the page

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-accessibility-passport#109]
Feedback from AAACT:
> When one actioned a link, the keyboard focus always went to the top of the page and the user always sees the heading GC workplace Accessibility passport heading then one needs to go down to the bottom third of the page to see the actual content of the link they actioned.

**Comment by mnigh** [comment]
Could this be the sole hash href (#) placeholders?

**Comment by JoshBeveridge** [comment]
I'd agree with @mnigh that this is likely due to an anchor having an empty hash (`#`) somewhere. I'll need more information about the technical implementation of this anchor before I can provide any further advice.
