### ISSUE TITLE
Blue buttons do not have a visible focus state

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-accessibility-passport#114]
From AAACT:

> One error was found on a page outside of the scope of the report that is still worth mentioning:
 https://gc-accessibility-passport-psi.vercel.app/passport 

> The blue links do not have a visible focus state. The black border, the only focus state change, has a contrast ratio of 2.6:1 against the adjacent blue background colour. The minimum contrast is 3:1. There are no indications of state change to supplement the non-conforming interior black border.

### Screenshot
![image.png](https://images.zenhubusercontent.com/5f7b33373ac7b7279de9a3c5/99d1edfc-20ab-40e0-9d85-df6695ba6a9e)

**Comment by JoshBeveridge** [comment]
The reality is that focus states will have to be entirely redesigned at some point for all components (this likely applies to the Digital Talent platform as well). If this is the only instance in the prototype where the focus state is an issue, as a temporary fix until we produce a more comprehensive design language for the app, we can add an interior border that is white to create a contrast ring.
![image.png](https://images.zenhubusercontent.com/5defaea65418285f1f32e700/3a6a2960-66b3-4837-aeb6-773563dba21d)
This can be accomplished by using a double `box-shadow` value like the following:
`box-shadow: 0 0 0 3px white, 0 0 0 6px darkblue`
