### ISSUE TITLE
Change "login" to "sign-in", "logout" to "sign out"

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-accessibility-passport#126]
### Acceptance Criteria
- [ ] text should read _Sign in_ instead of _Login_
- [ ] text should read _Sign out_ instead of _Logout_
- [ ] route should be `/sign-in` instead of `/login`
- [ ] route should be `/sign-out` instead of `/logout`

**Comment by mnigh** [comment]
@gobyrne is this issue referring to the text (_Login_ to _Sign in_), the route (`/login` to `/sign-in`), or both?

**Comment by gobyrne** [comment]
It was referring to the text. Not a terrible idea to do both though.

**Comment by mnigh** [comment]
> It was referring to the text. Not a terrible idea to do both though.

@gobyrne Thanks for the clarification. I just realized that if we changed _Login_ to _Sign in_, _Logout_ also should be changed to _Sign out_ and `/sign-out`: does that make sense?

**Comment by gobyrne** [comment]
yes
