### ISSUE TITLE
Bug - Keyboard navigation not completely working on Register

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-accessibility-passport#127]

**Comment by gobyrne** [comment]
Tester note - I activated the Register link and entered my info to create an account. I was able to navigate to the input fields using the Tab key and type in my information. However, other ways of navigating with the keyboard such as trying to find the input fields by typing the letter E did not work as well.

**Comment by mnigh** [comment]
> However, other ways of navigating with the keyboard such as trying to find the input fields by typing the letter E did not work as well.

@JoshBeveridge @gobyrne is this standard practice for those using screen readers? I haven't encountered this feature before.

**Comment by mnigh** [comment]
Cannot reproduce this behaviour, could be fixed.
