### ISSUE TITLE
Remove "The barriers below require your attention"

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-accessibility-passport#137]
On the employee dashboard we there is a banner that says "The barriers below require your attention".

@JoshBeveridge I assume you added this as an example of how we could highlight things that require action for users. But where we are now is that it's not clear how or why to take action on these barriers.

I suggest we remove this until we have a clear way to demonstrate how it could be useful.

**Comment by JoshBeveridge** [comment]
Basically, I was thinking that barriers that have been actioned by your manager but require the owner's sign off would show up here as a part of the two-way confirmation described in our conversations with OPSA. It's true however, that as static content, this might not be immediately obvious as is. We could add helper text below the title, or we can remove it for now until we have a better sense of the sign off process and whether it works for both owners and managers.

**Comment by gobyrne** [comment]
Yeah, let's remove. I get the sense that sign-off could change a lot anyway.

**Comment by mnigh** [comment]
@gobyrne @JoshBeveridge is "The barriers below require your attention" to be removed from both the employee (`/passport`) and the manager dashboard (`/manager/view-employee-passport`) or just the employee dashboard?

**Comment by gobyrne** [comment]
Both, thanks for finding
