### ISSUE TITLE
Remove "right" as a description for where things are situated on the page

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-accessibility-passport#140]
This text appears on the review-barrier page (/passport/barriers/review-barrier)
> You can select the links in the upper right-hand corner of each solution box to view details, edit its content, or delete it from your Passport.

Let's update it to:
"Links to view, edit or delete each of the solutions linked to this barrier are provided."

Also, let's search through all the text for "right" and similarly remove it.

**Comment by gobyrne** [comment]
This text appears on the review-barrier page (/passport/barriers/review-barrier)
> You can select the links in the upper right-hand corner of each solution box to view details, edit its content, or delete it from your Passport.

Let's update it to:
"Links to view, edit or delete each of the solutions linked to this barrier are provided."

**Comment by mnigh** [comment]
@gobyrne Found another one on `/manager/view-employee-barrier`:
> You can select the links in the upper right-hand corner of each solution box to view or act on the solutions.

![Screen Shot 2022-05-27 at 10 48 26](https://user-images.githubusercontent.com/3046459/170723789-00998753-1430-472b-aad5-fd18773fafbf.png)

What would you like to replace that copy with?

**Comment by gobyrne** [comment]
Let's just remove the second sentence for now.

**Comment by mnigh** [comment]
@gobyrne What about other directional language such as **above**, does that need to be changed and if so to what? Here are two instances:

- /manager/view-employee-solution
- /passport/barriers/solutions/review-solution

### Screenshots
![Screen Shot 2022-05-27 at 11 08 16](https://user-images.githubusercontent.com/3046459/170727620-8610ccaa-9ff8-4568-bf74-f6b64f5bb7d8.png)
![Screen Shot 2022-05-27 at 11 02 23](https://user-images.githubusercontent.com/3046459/170727622-886e2b0c-e3ff-4677-8a54-fe3679363366.png)

**Comment by gobyrne** [comment]
"Above" is actually ok. Text navigation is linear, so there's an above and below. But it's only 1 dimension (instead of two), so there's no "right" or "left".
