### ISSUE TITLE
Revise copy for passport agreement

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-accessibility-passport#141]
Design changes need to be made to reflect that the manager is not a gatekeeper, but rather a facilitator. This UI and the manager UI should reflect an acknowledgement from the manager that they will action this solution within the Workplace Accommodation process

Revise the design and the copy to reflect the purpose of the tool: to document the Barriers, solution and an agreement between the employee and manager on what will be actioned.

**Comment by RM-1978** [comment]
Hello to be inclusive of non-european cultures in our user-testing, please change the following names:
1) Tracy Huddle  - needs to change to Sikku Aariak 
2) Shannon Ghiles - to Taylor Ghiles (Gender fluid person)
3) Jennifer Rotterdam - to Samira Hana
