### ISSUE TITLE
Missing French translations

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-accessibility-passport#160]

**Comment by mnigh** [comment]
Some of the translation strings were merged in as part of [this PR](https://github.com/GCTC-NTGC/gc-accessibility-passport/blob/version-5.0.0/lang/fr.json), but more strings are waiting to come back from translation services.

**Comment by RM-1978** [comment]
@mnigh and @gobyrne The first set of translation strings were reviewed by OPSA.  See below for changes in both official languages: 

EN: 
[https://app.zenhub.com/files/477804994/b8d3d26f-67a2-480d-b019-3358b0106cac/download](https://app.zenhub.com/files/477804994/b8d3d26f-67a2-480d-b019-3358b0106cac/download)

FR:
[https://app.zenhub.com/files/477804994/a46b8b1c-ba35-4200-abd4-ca1482245f6f/download](https://app.zenhub.com/files/477804994/a46b8b1c-ba35-4200-abd4-ca1482245f6f/download)

**Comment by RM-1978** [comment]
@mnigh and @gobyrne, here is the second set of verified translation strings: 

EN: 
[https://app.zenhub.com/files/477804994/a0374d7d-bc61-4d51-b39c-c1efcd4acd5c/download](https://app.zenhub.com/files/477804994/a0374d7d-bc61-4d51-b39c-c1efcd4acd5c/download)

FR: 
[https://app.zenhub.com/files/477804994/ba0aaea6-a33b-42a4-8a3a-82083e5abf18/download](https://app.zenhub.com/files/477804994/ba0aaea6-a33b-42a4-8a3a-82083e5abf18/download)
