### ISSUE TITLE
Passport page copy to be changed

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-accessibility-passport#168]
![Screen Shot 2022-06-03 at 10 16 30](https://user-images.githubusercontent.com/3046459/171872155-c613f505-625d-43f5-9b90-8271a5ecd6a0.png)

**Comment by JoshBeveridge** [comment]
I'd probably propose something along the lines of:
# Barriers in my passport
Below are the barriers you've added to your passport, categorized by whether or not solutions have been actioned for them. You can click on a particular barrier's name or it's associated "view" button to be taken to a more detailed view about the barrier, it's history in your passport, and the solutions that you've proposed for it.
## Barriers with working solutions in place
[Barrier list]
## Barriers with solutions in progress
[Barrier list]

@RM-1978 do you mind giving this a quick once over to make sure I'm not going too far out there?
