### ISSUE TITLE
Ensure that all AAACT- related fixes for  the English carry through to the French

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-accessibility-passport#183]

**Comment by mnigh** [comment]
@RM-1978 were there specific fixes that have already been made from [the list](https://github.com/GCTC-NTGC/gc-accessibility-passport/issues/104#issuecomment-1137427445) that did not carry through to when the site is toggled to French? Some of the issues are not yet in the "Ready For Dev" column, but in any case, none of these issues are not related to French translations.
