### ISSUE TITLE
Missing translations for Home page links

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-accessibility-passport#185]
We are missing the following URLs from the Home page in French and some in English where we currently using a placeholder of `#`:

### For employees
- Employee link # 3 (French)
- Employee link # 4 (French)
- Employee link # 5 (French, English)
- Employee link # 6 (French, English)

### For Managers
- Manager link # 1 (French)
- Manager link # 2 (French)
- Manager link # 3 (French)
- Manager link # 4 (French, English)
- Manager link # 5 (French, English)

### Screenshot
![Screen Shot 2022-06-14 at 13 59 33](https://user-images.githubusercontent.com/3046459/173659516-ce397cc2-01f4-4fa6-a525-922586bb008c.png)

**Comment by mnigh** [comment]
@RM-1978 would you be able to provide these URLs?

**Comment by RM-1978** [comment]
Hi @mnigh, I included the links to the Passport Canada Site  and the form in the other issue.
