### ISSUE TITLE
Spike - Deploy to different URL (while conserving the old one)

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-accessibility-passport#193]

**Comment by mnigh** [comment]
- https://gc-accessibility-passport-dev.vercel.app/ all the upcoming PRs will be merged in here until further decision.
- https://gc-accessibility-passport-psi.vercel.app/ would still remain the current production version for UAT.

**Comment by brindasasi** [comment]
thanks @mnigh !
