### ISSUE TITLE
Dev - Home page

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/gc-accessibility-passport#27]

**Comment by RM-1978** [comment]
Good morning! Please find the  content/copy we needed for the home page: [https://app.zenhub.com/files/477804994/fcbd6fc1-9c27-4897-85e6-e53e745b5bf8/download](https://app.zenhub.com/files/477804994/fcbd6fc1-9c27-4897-85e6-e53e745b5bf8/download)
