### ISSUE TITLE
Dev - Edit manager information page

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/gc-accessibility-passport#35]

**Comment by RM-1978** [comment]
Recommendations: 
[https://app.zenhub.com/files/477804994/b1959237-9ca0-410f-886a-334bffb4a01e/download](https://app.zenhub.com/files/477804994/b1959237-9ca0-410f-886a-334bffb4a01e/download)
*Please note that if there is a feature or text in the designs upon which we have not remarked, please keep it as it is :)

**Comment by brindasasi** [comment]
https://gc-accessibility-passport-9iqzkatlc-brindasasi.vercel.app/managerInfo

**Comment by brindasasi** [comment]
Known issues that I need consultation with 
Ruler isn't coming
I use the same footer as in Identify Barrier page but the ruler isn't coming.
Button style is not one of valid props
  The style in the mock isn't the same we use in common components and it doesn't have that grey color as prop. Do we want to add that into common component? Or I'm missing something? (edited)

**Comment by yonikid15** [comment]
Links for OPSA review instructions:
1. First [login](https://gc-accessibility-passport-jytxw6eaz-brindasasi.vercel.app/login) using any name or email now. 
- Click on link to: [Manager info form](https://gc-accessibility-passport-git-fea-7e5b40-accessibility-passport.vercel.app/manager-info)

**Comment by RM-1978** [comment]
Not quite yet

**Comment by RM-1978** [comment]
OPSA Review (https://gc-accessibility-passport-9iqzkatlc-brindasasi.vercel.app/managerInfo): [https://app.zenhub.com/files/477804994/fb34d654-5ac9-4471-9b22-83891f2e0bf2/download](https://app.zenhub.com/files/477804994/fb34d654-5ac9-4471-9b22-83891f2e0bf2/download)

**Comment by RM-1978** [comment]
For our Chat on the 27th :)
[https://app.zenhub.com/files/477804994/1d561bb9-bfa2-4f4a-9b9d-a0b6cbf36fcc/download](https://app.zenhub.com/files/477804994/1d561bb9-bfa2-4f4a-9b9d-a0b6cbf36fcc/download)

**Comment by RM-1978** [comment]
May 4: Note that OPSA will review all the UIs in the Passport User flow at once  on May 6 to approve or approve with minor changes. @JoshBeveridge @brindasasi @gobyrne @yonikid15
