### ISSUE TITLE
Dev - Identify a solution page (worksheet)

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/gc-accessibility-passport#38]

**Comment by RM-1978** [comment]
Recommendations: 
[https://app.zenhub.com/files/477804994/e8ae1b91-3e21-4f58-ab73-afeb0c12825a/download](https://app.zenhub.com/files/477804994/e8ae1b91-3e21-4f58-ab73-afeb0c12825a/download)
*Please note that if there is a feature or text in the designs upon which we have not remarked, please keep it as it is :)

**Comment by RM-1978** [comment]
My apologies, as per Thursday's meeting, there have been some slight updates (see green highlights) to follow a new solution- barrier relationship required from the OPSA team: [https://app.zenhub.com/files/477804994/56938e76-dd38-40be-9016-3ed661b99f5d/download](https://app.zenhub.com/files/477804994/56938e76-dd38-40be-9016-3ed661b99f5d/download)

**Comment by brindasasi** [comment]
.

**Comment by brindasasi** [comment]
.

**Comment by RM-1978** [comment]
Under OPSA review. will add team recommendations as soon as they are ready.
