### ISSUE TITLE
[Passport user] - Edit, review a barrier / add another solution page

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/gc-accessibility-passport#39]

**Comment by RM-1978** [comment]
Please find a link to the Review sheet for the Edit Review A barrier portion: 
https://www.gcpedia.gc.ca/wiki/GC_Accessibility_Training_and_Events_/_Formation_et_%C3%A9v%C3%A9nements_du_GC_sur_l%27accessibilit%C3%A9?setlang=en&uselang=en

**Comment by RM-1978** [comment]
Recommendations: [https://app.zenhub.com/files/477804994/f4884e53-384f-4773-af7f-26525827aadf/download](https://app.zenhub.com/files/477804994/f4884e53-384f-4773-af7f-26525827aadf/download)
*Same caveat as the other applies :)

**Comment by RM-1978** [comment]
May 4: Note that OPSA will review all the UIs in the Passport User flow at once  on May 6 to approve or approve with minor changes. @JoshBeveridge @brindasasi @gobyrne @yonikid15
