### ISSUE TITLE
[Manager] - View barrier container page

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/gc-accessibility-passport#42]

**Comment by RM-1978** [comment]
Review in progress.

**Comment by RM-1978** [comment]
Recommendations: [https://app.zenhub.com/files/477804994/e05d6112-1cd7-4141-a089-2072fb962e19/download](https://app.zenhub.com/files/477804994/e05d6112-1cd7-4141-a089-2072fb962e19/download)
Though we have removed the word Please because it is repetitive., we hope that is understood :)

**Comment by brindasasi** [comment]
@RM-1978 
the attached document is for #41 
This issue supposed to review 
https://www.figma.com/file/SqRfWwcyuclFvGCq47zJf6/Passport---V5.0.0?node-id=2%3A18

**Comment by RM-1978** [comment]
Hi Brinda,  thanks for the catch and your patience! I have updated the link above :)
