### ISSUE TITLE
[Manager] - View / action a solution page

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/gc-accessibility-passport#43]

**Comment by RM-1978** [comment]
Review in progress.

**Comment by RM-1978** [comment]
Thanks for your work! Recommendations: 
[https://app.zenhub.com/files/477804994/0c878857-8b3b-43be-929f-80c235801cd6/download](https://app.zenhub.com/files/477804994/0c878857-8b3b-43be-929f-80c235801cd6/download)

**Comment by brindasasi** [comment]
Assigning to you @yonikid15 as this is almost same as you are currently working on

**Comment by RM-1978** [comment]
May 4: Note that OPSA will review all the UIs in the Passport User flow at once  on May 6 to approve or approve with minor changes. @JoshBeveridge @brindasasi @gobyrne @yonikid15

**Comment by RM-1978** [comment]
May 4: Note that OPSA will review all the UIs in the Passport User flow at once  on May 6 to approve or approve with minor changes. @JoshBeveridge @brindasasi @gobyrne @yonikid15
