### ISSUE TITLE
Identify a new barrier (customization)

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-accessibility-passport#44]

**Comment by gggrant** [comment]
Recommended changes to the Page:
[https://app.zenhub.com/files/477804994/1f6440eb-a30d-492b-83e5-8fb0064629ae/download](https://app.zenhub.com/files/477804994/1f6440eb-a30d-492b-83e5-8fb0064629ae/download)
*Please note that if there is a feature or text in the designs upon which we have not remarked, please keep it as it is :)

**Comment by yonikid15** [comment]
Links for OPSA review instructions:
1. First [login](https://gc-accessibility-passport-jytxw6eaz-brindasasi.vercel.app/login) using any name or email now. 
- Click on links to either: [Identify a barrier](https://gc-accessibility-passport-jytxw6eaz-brindasasi.vercel.app/barriers/identify-a-barrier) or [Identify a barrier (cont.)](https://gc-accessibility-passport-jytxw6eaz-brindasasi.vercel.app/barriers/identify-a-barrier-2)

**Comment by brindasasi** [comment]
Change request after OPSA review has been added under https://github.com/GCTC-NTGC/gc-accessibility-passport/issues/57 . Hence closing this issue
