### ISSUE TITLE
Identify a solution (customization)

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-accessibility-passport#45]

**Comment by RM-1978** [comment]
Recommendations: 
[https://app.zenhub.com/files/477804994/effef6f9-d809-4bb4-b10d-508060fd286f/download](https://app.zenhub.com/files/477804994/effef6f9-d809-4bb4-b10d-508060fd286f/download)
* April 27 update: As discussed with Josh, please ensure that the example solution we have chosen for __Noise in the workplace_ appears in the information component for this UI. Please remove the optional context  component and its instructions.  @brindasasi  @yonikid15 @gobyrne @JoshBeveridge

**Comment by RM-1978** [comment]
Please draw on the Noise-cancelling headphones  example and definition in the tables attached to populate  the information text below : You've selected _"Noise-cancelling headphones" as a solution for Noise in the workplace.[https://app.zenhub.com/files/477804994/8ee479ef-5524-4391-8fe9-4c0357dc75a7/download](https://app.zenhub.com/files/477804994/8ee479ef-5524-4391-8fe9-4c0357dc75a7/download)
