### ISSUE TITLE
[Passport user] - View/action a solution page

### ISSUE THREAD

**Issue by JoshBeveridge** [GCTC-NTGC/gc-accessibility-passport#46]

**Comment by RM-1978** [comment]
Recommendations: [https://app.zenhub.com/files/477804994/41b5c3ea-6fba-43e4-ab1c-b8692e2204d0/download](https://app.zenhub.com/files/477804994/41b5c3ea-6fba-43e4-ab1c-b8692e2204d0/download)

**Comment by RM-1978** [comment]
May 4: Note that OPSA will review all the UIs in the Passport User flow at once  on May 6 to approve or approve with minor changes. @JoshBeveridge @brindasasi @gobyrne @yonikid15

**Comment by RM-1978** [comment]
May 4: Note that OPSA will review all the UIs in the Passport User flow at once  on May 6 to approve or approve with minor changes. @JoshBeveridge @brindasasi @gobyrne @yonikid15
