### ISSUE TITLE
OPSA REVIEW - Barrier Page Change Request

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-accessibility-passport#57]

**Comment by RM-1978** [comment]
Request Details :
[https://app.zenhub.com/files/477804994/770e8b9c-1f57-446a-8340-731139d67dfd/download](https://app.zenhub.com/files/477804994/770e8b9c-1f57-446a-8340-731139d67dfd/download)
@gobyrne @JoshBeveridge @yonikid15 @brindasasi

**Comment by RM-1978** [comment]
Hi @gobyrne @JoshBeveridge, @yonikid15  and @brindasasi ! Please note  the last  copy changes we have just received from OPSA: This one will then be good to go for the user pathway/flow.[https://app.zenhub.com/files/477804994/452c7b84-0173-46c6-974b-364f6c4f6dc6/download](https://app.zenhub.com/files/477804994/452c7b84-0173-46c6-974b-364f6c4f6dc6/download)t

**Comment by RM-1978** [comment]
Hi @gobyrne @JoshBeveridge, @yonikid15  and @brindasasi ! Please note  the recommended copy  changes we have just received from the OPSA team:[https://app.zenhub.com/files/477804994/96918390-ac33-43c5-b739-d9e79ec2a790/download](https://app.zenhub.com/files/477804994/96918390-ac33-43c5-b739-d9e79ec2a790/download)
Overall, thank you for your engagement with the design request! You were very kind to engage thoughtfully and meaningfully with change request we sent your way.

**Comment by RM-1978** [comment]
May 4: Note that OPSA will review all the UIs in the Passport User flow at once  on May 6 to approve or approve with minor changes. @JoshBeveridge @brindasasi @gobyrne @yonikid15

**Comment by brindasasi** [comment]
Reopening since we missed some changes from it
