### ISSUE TITLE
Dev - Identify a barrier/Identify a barrier (cont'd) revisions 

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-accessibility-passport#58]
[https://app.zenhub.com/files/477804994/2b9a67f3-ec53-4727-aab8-dfa98201b35c/download](https://app.zenhub.com/files/477804994/2b9a67f3-ec53-4727-aab8-dfa98201b35c/download)

**Comment by brindasasi** [comment]
As per Rosali's suggestion I installed axe browser extension and it caught few accessibility issues on this page like in the pic. Pls take a look at them 
<img width="588" alt="Screen Shot 2022-04-27 at 12 30 56 PM" src="https://user-images.githubusercontent.com/89482910/165568487-76e6569d-e3be-4a57-9fa7-b441b0ca7afd.png">

**Comment by RM-1978** [comment]
May 4: Note that OPSA will review all the UIs in the Passport User flow at once  on May 6 to approve or approve with minor changes. @JoshBeveridge @brindasasi @gobyrne @yonikid15
