### ISSUE TITLE
Dev - Identify a new barrier (worksheet) page

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-accessibility-passport#9]
Build ["Identify a barrier"](https://www.figma.com/proto/SqRfWwcyuclFvGCq47zJf6/Passport---V5.0.0?node-id=2%3A8&scaling=min-zoom&page-id=0%3A1) page.

**Comment by RM-1978** [comment]
Recommended changes to the Page: 
[https://app.zenhub.com/files/477804994/3b4371dc-261f-47d6-8d3f-cb3152536b9e/download](https://app.zenhub.com/files/477804994/3b4371dc-261f-47d6-8d3f-cb3152536b9e/download)
*Please note that if there is a feature or text in the designs upon which we have not remarked, please keep it as it is :)

**Comment by yonikid15** [comment]
Links for OPSA review instructions:
1. First [login](https://gc-accessibility-passport-jytxw6eaz-brindasasi.vercel.app/login) using any name or email now. 
- Click on links to either: [Identify a barrier](https://gc-accessibility-passport-jytxw6eaz-brindasasi.vercel.app/barriers/identify-a-barrier) or [Identify a barrier (cont.)](https://gc-accessibility-passport-jytxw6eaz-brindasasi.vercel.app/barriers/identify-a-barrier-2)

**Comment by brindasasi** [comment]
Change request after OPSA review has been added under https://github.com/GCTC-NTGC/gc-accessibility-passport/issues/57 . Hence closing this issue
