### ISSUE TITLE
Invalid and non-matching href values

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-accessibility-passport#99]
When loading the root route, the following errors appear in the console:
- Prop `href` did not match. Server: "manager/manager-dashboard" Client: "/manager/manager-dashboard
- Invalid href passed to next/router: //, repeated forward-slashes (//) or backslashes \ are not valid in the href

### Screenshot
![Screen Shot 2022-05-18 at 10 21 13](https://user-images.githubusercontent.com/3046459/169065144-0919f53f-dcb9-43af-ae49-b74889daa06f.png)

**Comment by brindasasi** [comment]
thank you for fixing that @mnigh !
